baseURL = "http://chadwelch.com/"
languageCode = "en-us"
title = "Chad Welch"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Chad Welch"
    description = "Software Developer"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/experience/"
    name = "Experience"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/chdwlch/"
    name = "fab fa-github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/chdwlch/"
    name = "fab fa-twitter"
    weight = 2

[[menu.icon]]
    url = "https://nostr.com/npub1aypcuyy3dkgss6wmvmeung05z56evucgk37wxymvnrc6dg32v9gqez0hdf"
    name = "fab fa-neos"
    weight = 3